// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
// ignore: depend_on_referenced_packages
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARF9Ny99bNeP0IqLRwWGO6qVCpixetACU',
    appId: '1:604846926162:web:8dd4515a73969b4496b28b',
    messagingSenderId: '604846926162',
    projectId: 'bring-the-menu',
    authDomain: 'bring-the-menu.firebaseapp.com',
    storageBucket: 'bring-the-menu.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHWXk6Nnud8dNiXJjNaYVdIr9yjWjeL5U',
    appId: '1:604846926162:android:dde2932d81b7ee2b96b28b',
    messagingSenderId: '604846926162',
    projectId: 'bring-the-menu',
    storageBucket: 'bring-the-menu.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBI4vQI_Ns4QnkkZaVHK1Guvz9CLkw0uLQ',
    appId: '1:604846926162:ios:b724cc1680419f7696b28b',
    messagingSenderId: '604846926162',
    projectId: 'bring-the-menu',
    storageBucket: 'bring-the-menu.appspot.com',
    iosClientId:
        '604846926162-n95tnn37172m89c3ff3fe3n2ftrh1h91.apps.googleusercontent.com',
    iosBundleId: 'com.example.bringTheMenu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBI4vQI_Ns4QnkkZaVHK1Guvz9CLkw0uLQ',
    appId: '1:604846926162:ios:b724cc1680419f7696b28b',
    messagingSenderId: '604846926162',
    projectId: 'bring-the-menu',
    storageBucket: 'bring-the-menu.appspot.com',
    iosClientId:
        '604846926162-n95tnn37172m89c3ff3fe3n2ftrh1h91.apps.googleusercontent.com',
    iosBundleId: 'com.example.bringTheMenu',
  );
}
